version: '3.7'

networks: 
  internal:
    external: false

services:

  nodejs:
    image: myuserindocker/radioscanner-webapp-nodejs:latest
    environment:
      DEPLOYMENT: production
    ports: 
      - 80:80
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - internal

  apachestreamproxy:
    image: myuserindocker/radioscanner-webapp-apachestreamproxy:latest
    environment:
      DEPLOYMENT: production
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - internal
